import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
      animation: {
        fadeIn: "fadeIn 1s ease-in-out",
        fadeOut: "fadeOut 1s ease-in-out",
        zoomIn: "zoomIn 1s ease-in-out",
        zoomOut: "zoomOut 1s ease-in-out",
        slideInLeft: "slideInLeft 1s ease-in-out",
        slideInRight: "slideInRight 1s ease-in-out",
        slideInUp: "slideInUp 1s ease-in-out",
        slideInDown: "slideInDown 1s ease-in-out",
        bounceIn: "bounceIn 1s ease-in-out",
        rotateIn: "rotateIn 1s ease-in-out",
        flipInX: "flipInX 1s ease-in-out",
        pulse: "pulse 1s ease-in-out infinite",
        bounceOut: "bounceOut 1s ease-in-out",
        shake: "shake 0.6s ease-in-out infinite",
        swing: "swing 1s ease-in-out infinite",
        flipInY: "flipInY 1s ease-in-out",
        zoomInDown: "zoomInDown 1s ease-in-out",
        zoomOutDown: "zoomOutDown 1s ease-in-out",
        fadeInUp: "fadeInUp 1s ease-in-out",
        fadeInDown: "fadeInDown 1s ease-in-out",
        slideOutLeft: "slideOutLeft 1s ease-in-out",
        slideOutRight: "slideOutRight 1s ease-in-out",
        slideOutUp: "slideOutUp 1s ease-in-out",
        slideOutDown: "slideOutDown 1s ease-in-out",
        rollIn: "rollIn 1s ease-in-out",
        rollOut: "rollOut 1s ease-in-out",
        fadeInLeft: "fadeInLeft 1s ease-in-out",
        fadeInRight: "fadeInRight 1s ease-in-out",
        lightSpeedIn: "lightSpeedIn 1s ease-in-out",
        lightSpeedOut: "lightSpeedOut 1s ease-in-out",
        tada: "tada 1s ease-in-out infinite",
        bounceInDown: "bounceInDown 1s ease-in-out",
        bounceInLeft: "bounceInLeft 1s ease-in-out",
        bounceInRight: "bounceInRight 1s ease-in-out",
        flipOutX: "flipOutX 1s ease-in-out",
        flipOutY: "flipOutY 1s ease-in-out",
        zoomInLeft: "zoomInLeft 1s ease-in-out",
        zoomOutLeft: "zoomOutLeft 1s ease-in-out",
        zoomInRight: "zoomInRight 1s ease-in-out",
        zoomOutRight: "zoomOutRight 1s ease-in-out",
        fadeInZoom: "fadeInZoom 1s ease-in-out",
        fadeOutZoom: "fadeOutZoom 1s ease-in-out",
        slideUp: "slideUp 1s ease-in-out",
        slideDown: "slideDown 1s ease-in-out",
        swingRight: "swingRight 1s ease-in-out infinite",
        swingLeft: "swingLeft 1s ease-in-out infinite",
        fadeInRightBig: "fadeInRightBig 1s ease-in-out",
        fadeOutLeftBig: "fadeOutLeftBig 1s ease-in-out",
        flipOutUp: "flipOutUp 1s ease-in-out",
        flipOutDown: "flipOutDown 1s ease-in-out",
      },      
      keyframes: {
        fadeIn: { from: { opacity: "0" }, to: { opacity: "1" } },
        fadeOut: { from: { opacity: "1" }, to: { opacity: "0" } },
        zoomIn: { from: { transform: "scale(0.8)", opacity: "0" }, to: { transform: "scale(1)", opacity: "1" } },
        zoomOut: { from: { transform: "scale(1)", opacity: "1" }, to: { transform: "scale(0.8)", opacity: "0" } },
        slideInLeft: { from: { transform: "translateX(-100%)" }, to: { transform: "translateX(0)" } },
        slideInRight: { from: { transform: "translateX(100%)" }, to: { transform: "translateX(0)" } },
        slideInUp: { from: { transform: "translateY(100%)" }, to: { transform: "translateY(0)" } },
        slideInDown: { from: { transform: "translateY(-100%)" }, to: { transform: "translateY(0)" } },
        bounceIn: {
          "0%": { transform: "scale(0.5)", opacity: "0" },
          "50%": { transform: "scale(1.2)", opacity: "1" },
          "100%": { transform: "scale(1)" },
        },
        rotateIn: { from: { transform: "rotate(-90deg)", opacity: "0" }, to: { transform: "rotate(0)", opacity: "1" } },
        flipInX: {
          "0%": { transform: "rotateX(90deg)", opacity: "0" },
          "100%": { transform: "rotateX(0)", opacity: "1" },
        },
        pulse: {
          "0%, 100%": { transform: "scale(1)", opacity: "1" },
          "50%": { transform: "scale(1.1)", opacity: "0.8" },
        },
        bounceOut: { "0%": { transform: "scale(1)" }, "100%": { transform: "scale(0)" } },
        shake: {
          "0%": { transform: "translateX(0)" },
          "25%": { transform: "translateX(-4px)" },
          "50%": { transform: "translateX(4px)" },
          "75%": { transform: "translateX(-4px)" },
          "100%": { transform: "translateX(0)" },
        },
        swing: {
          "0%": { transform: "rotate(-15deg)" },
          "50%": { transform: "rotate(15deg)" },
          "100%": { transform: "rotate(-15deg)" },
        },
        flipInY: {
          "0%": { transform: "rotateY(90deg)", opacity: "0" },
          "100%": { transform: "rotateY(0)", opacity: "1" },
        },
        zoomInDown: { from: { transform: "scale(0.8) translateY(-100%)" }, to: { transform: "scale(1) translateY(0)" } },
        zoomOutDown: { from: { transform: "scale(1) translateY(0)" }, to: { transform: "scale(0.8) translateY(100%)" } },
        fadeInUp: { from: { opacity: "0", transform: "translateY(10px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        fadeInDown: { from: { opacity: "0", transform: "translateY(-10px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        slideOutLeft: { from: { transform: "translateX(0)" }, to: { transform: "translateX(-100%)" } },
        slideOutRight: { from: { transform: "translateX(0)" }, to: { transform: "translateX(100%)" } },
        slideOutUp: { from: { transform: "translateY(0)" }, to: { transform: "translateY(-100%)" } },
        slideOutDown: { from: { transform: "translateY(0)" }, to: { transform: "translateY(100%)" } },
        rollIn: { from: { transform: "rotate(90deg)" }, to: { transform: "rotate(0)" } },
        rollOut: { from: { transform: "rotate(0)" }, to: { transform: "rotate(90deg)" } },
        fadeInLeft: { from: { opacity: "0", transform: "translateX(-10px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        fadeInRight: { from: { opacity: "0", transform: "translateX(10px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        lightSpeedIn: { from: { transform: "translateX(100%)", opacity: "0" }, to: { transform: "translateX(0)", opacity: "1" } },
        lightSpeedOut: { from: { transform: "translateX(0)", opacity: "1" }, to: { transform: "translateX(100%)", opacity: "0" } },
        tada: {
          "0%": { transform: "scale(1)" },
          "10%, 20%": { transform: "rotate(-10deg)" },
          "30%, 50%, 70%, 90%": { transform: "rotate(10deg)" },
          "40%, 60%, 80%": { transform: "rotate(-10deg)" },
          "100%": { transform: "scale(1)" },
        },
        bounceInDown: {
          "0%": { transform: "translateY(-3000px)" },
          "60%": { transform: "translateY(30px)" },
          "100%": { transform: "translateY(0)" },
        },
        bounceInLeft: {
          "0%": { transform: "translateX(-3000px)" },
          "60%": { transform: "translateX(30px)" },
          "100%": { transform: "translateX(0)" },
        },
        bounceInRight: {
          "0%": { transform: "translateX(3000px)" },
          "60%": { transform: "translateX(-30px)" },
          "100%": { transform: "translateX(0)" },
        },
        flipOutX: {
          "0%": { transform: "rotateX(0)", opacity: "1" },
          "100%": { transform: "rotateX(90deg)", opacity: "0" },
        },
        flipOutY: {
          "0%": { transform: "rotateY(0)", opacity: "1" },
          "100%": { transform: "rotateY(90deg)", opacity: "0" },
        },
        zoomInLeft: { from: { transform: "scale(0.8) translateX(-100%)" }, to: { transform: "scale(1) translateX(0)" } },
        zoomOutLeft: { from: { transform: "scale(1) translateX(0)" }, to: { transform: "scale(0.8) translateX(-100%)" } },
        zoomInRight: { from: { transform: "scale(0.8) translateX(100%)" }, to: { transform: "scale(1) translateX(0)" } },
        zoomOutRight: { from: { transform: "scale(1) translateX(0)" }, to: { transform: "scale(0.8) translateX(100%)" } },
        fadeInZoom: { from: { opacity: "0", transform: "scale(0.8)" }, to: { opacity: "1", transform: "scale(1)" } },
        fadeOutZoom: { from: { opacity: "1", transform: "scale(1)" }, to: { opacity: "0", transform: "scale(0.8)" } },
        slideUp: { from: { transform: "translateY(100%)" }, to: { transform: "translateY(0)" } },
        slideDown: { from: { transform: "translateY(-100%)" }, to: { transform: "translateY(0)" } },
        swingRight: {
          "0%": { transform: "rotate(0)" },
          "50%": { transform: "rotate(20deg)" },
          "100%": { transform: "rotate(0)" },
        },
        swingLeft: {
          "0%": { transform: "rotate(0)" },
          "50%": { transform: "rotate(-20deg)" },
          "100%": { transform: "rotate(0)" },
        },
        fadeInRightBig: { from: { opacity: "0", transform: "translateX(50px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        fadeOutLeftBig: { from: { opacity: "1", transform: "translateX(0)" }, to: { opacity: "0", transform: "translateX(-50px)" } },
        flipOutUp: {
          "0%": { transform: "rotateX(0)", opacity: "1" },
          "100%": { transform: "rotateX(90deg)", opacity: "0" },
        },
        flipOutDown: {
          "0%": { transform: "rotateX(0)", opacity: "1" },
          "100%": { transform: "rotateX(-90deg)", opacity: "0" },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
